### ISSUE TITLE
Create GetUsers() method in repository

### ISSUE THREAD

**Issue by edvaudin** [edvaudin/CSharpAcademyBot#4]
The GetUsers() method should also include their reputation in the query.

**Comment by brun32700** [comment]
This is solved by PR #16, I accidently added it to main and it was included in that PR too. Sorry for the confusion, still getting hang of it.

![image](https://user-images.githubusercontent.com/48837066/228310411-8db1b600-64f2-4f15-8e17-bd12fb63067e.png)
